### ISSUE TITLE
Update documentation with unambiguous instructions to get a working development environment set up

### ISSUE THREAD

**Issue by msuriar** [tylerni7/missile-tid#23]
# Summary

Currently, the most detailed instructions for starting contributions to the project are in `CONTRIBUTING.rst`, but following them on a current install of (at least) Ubuntu doesn't result in a working development environment.

# Reproduction instructions

- Start with a fresh install of Ubuntu Karmic (22.10).
- Set up a base Python development environment.
- Clone repo
- Follow instructions in `CONTRIBUTING.rst` to get a development environment set up.
- Run tests

## Expected behaviour

- Tests run successfully, and pass.

## Actual behaviour

- Tests fail with `ImportError` and `ModuleNotFound` exceptions.

Furthermore, when attempting to satisfy dependencies/requirements by explicitly running `pip3 install -r requirements.txt`, module `pycurl` is not downloaded and run successfully.

### Python packages

```
$ sudo apt install python3-pip
$ sudo apt install build-essential libssl-dev libffi-dev python3-dev
$ sudo apt install python3-venv
```

### Repo/virtualenv setup

```
$ cd src
$ git clone https://github.com/tylerni7/missile-tid.git
$ cd missile-tid
$ python3 -m venv .venv
$ . ./.venv/bin/activate
```

### TID stuff

```
$ python setup.py develop
$ python setup.py test
```

(Fails with import errors, modules not found etc, notably for `pytest` which is explicitly specified in `requirements-dev.txt`

```
======================================================================
ERROR: tid.tests.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tid.tests.test_utils
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ms/src/missile-tid/tid/tests/test_utils.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'


----------------------------------------------------------------------
```

Attempted to resolve by manually installing modules in `requirements-dev.txt`

```
$ pip3 install -r requirements-dev.txt
$ python setup.py test
```

(Still fails with module imports, but this time only for laika etc, stuff listed in `requirements.txt`)

Try to manually install the stuff listed in `requirements.txt`

```
$ pip3 install -r requirements.txt
```

(Fails to complete successfully, bombing out when attempting to install `pycurl`).

```Collecting pycurl
  Downloading pycurl-7.45.2.tar.gz (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.2/234.2 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-9q_tu02w/pycurl_0118071d89e24b3397450d243196fd93/setup.py", line 229, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9q_tu02w/pycurl_0118071d89e24b3397450d243196fd93/setup.py", line 970, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
        File "/tmp/pip-install-9q_tu02w/pycurl_0118071d89e24b3397450d243196fd93/setup.py", line 634, in get_extension
          ext_config = ExtensionConfiguration(argv)
        File "/tmp/pip-install-9q_tu02w/pycurl_0118071d89e24b3397450d243196fd93/setup.py", line 93, in __init__
          self.configure()
        File "/tmp/pip-install-9q_tu02w/pycurl_0118071d89e24b3397450d243196fd93/setup.py", line 234, in configure_unix
          raise ConfigurationError(msg)
      __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by msuriar** [comment]
Right, the `pycurl` thing is actually a missing OS level dependency.

A bit of searching found https://stackoverflow.com/a/24051044

> On Debian I needed the following packages to fix this
>
> ```
> sudo apt install libcurl4-openssl-dev libssl-dev
> ```

That just leaves us with all the module not found exceptions.

**Comment by jmccartin** [comment]
We really could use a Dockerfile in order to streamline this - I had some issues getting the packages installed on my end (Ubuntu 20.04/WSL), but after trying a few things it seems like it has succeeded.

**Comment by MGNute** [comment]
I just did a clean install of the library today and should be able to update the docs at least somewhat. In my case the pycurl issue was solved by running a fresh `conda install pycurl`, which is odd because it said it had been installed before and it was in the requirements file. I also ran into the cartopy `free()` error mentioned in the main readme, plus the configuration.yml issue that I opened earlier today. But based on those I think I should be able to write up some more detailed instructions and stick them in the readme and generally update the docs to be consistent.

**Comment by MGNute** [comment]
> TID stuff
$ python setup.py develop
$ python setup.py test
(Fails with import errors, modules not found etc, notably for pytest which is explicitly specified in requirements-dev.txt

I don't think we currently have a `setup.py` file in there, so I'm assuming this was before that was removed? I did not encounter the pytest error today at least.

**Comment by MGNute** [comment]
#37
