### ISSUE TITLE
Deprecate use of setup.py and migrate build/packaging information to pyproject.toml

### ISSUE THREAD

**Issue by msuriar** [tylerni7/missile-tid#24]
`pyproject.toml` was introduced in [PEP 518](https://peps.python.org/pep-0518/) in 2016, and is intended to be a machine consumable file for specifying what build tools and dependencies are required.

We already have a `pyproject.toml`, but we're only using it for `mypy` and `pylint`. We should create a `setup.cfg`, add a `[build-system]` section to `pyproject.toml`, and then get rid of `setup.py`.

See e.g. [this post](https://snarky.ca/what-the-heck-is-pyproject-toml/) or [this one](https://towardsdatascience.com/setuptools-python-571e7d5500f2) for more background.

**Comment by msuriar** [comment]
How to configure `setuptools` with `pyproject.toml`: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

**Comment by jmccartin** [comment]
This could be used to fix the incorrect usage of the requirements files in the project too. From the setuptools and pypi documentation, we should have a section in `pyproject.toml` that tracks the 3rd party dependencies, without hard version locks. Eg:

```
[project]
# ...
dependencies = [
    "georinex",
    "h5py"
]
```

The `requirements.txt` and `requirements-dev.txt` files would then have the specific version locks to help with the build tools. The difference between the two files would be simply down to extra test and linting libraries that aren't required to run the actual project code.
