### ISSUE TITLE
i meet this problem no orbit data found

### ISSUE THREAD

**Issue by zhouyu00** [tylerni7/missile-tid#35]
![截图 2023-04-09 01-27-36](https://user-images.githubusercontent.com/11349435/230734860-556a89b5-50da-44e6-89d3-e29ef629926a.png)

**Comment by noaham** [comment]
@zhouyu00 can you please provide some details about your system and install? I believe you are running into an issue with Laika. Can you please run through the [Laika walkthrough](https://github.com/commaai/laika/blob/master/examples/Walkthrough.ipynb) and tell us if it completes successfully or where it fails.
